### ISSUE TITLE
Turn a line into a comment

### ISSUE THREAD

**Issue by Alphapage** [davidbonnet/astravel#2]
Hello,

Does astravel support such a feature ?

``` js
// turn next line to comment
var test;
```

like this:

``` js
// turn next line to comment
//var test;
```

Thanks in advance for your help.

**Comment by davidbonnet** [comment]
This involves modifying nodes based on the comment attached to it. In your example, the comment above would be attached to the node containing the variable declaration below. Turning that node into a comment would require merging it with the previous comment and attaching that comment to the next node, if any, or to the parent node. A tricky use case but interesting nonetheless.

Right now, `astravel` does not support node replacements, which would support your use case. This feature is however planned for version `0.4`, with an expected release in March.
