### ISSUE TITLE
Require error

### ISSUE THREAD

**Issue by Alphapage** [davidbonnet/astravel#3]
Hello,

I'm trying to play with astravel without success because it requires some files from dist folder: maybe you need to derequire before publishing the module with browserify.

Thanks in advance for your help or tell me if I'm wrong.

**Comment by Alphapage** [comment]
Sorry, my mistake I was using the wrong parameter in my packaging tool.
Finally, I used the src files instead of dist one.
You should publish the src folder to let other tools import es6 files instead of es5 browserified one.

Excuse me again.

**Comment by davidbonnet** [comment]
You are right! Feel free to make a pull request, otherwise I will try to do it at some point during the week-end.
