### ISSUE TITLE
Minified build contains source map

### ISSUE THREAD

**Issue by mootari** [davidbonnet/astravel#32]
About half of the [minified browser build](https://cdn.jsdelivr.net/npm/astravel@0.5.0/dist/astravel.min.js) is made up of a base64 encoded sourcemap. I'm not entirely sure if this was intentional or not, hence this issue.

**Comment by davidbonnet** [comment]
Thanks @mootari for raising that issue. You can now import it without source maps:
```html
<script type="module">
      import * as astravel from 'https://cdn.skypack.dev/astravel'
      window.astravel = astravel
</script>
```
