### ISSUE TITLE
Support for spread operator

### ISSUE THREAD

**Issue by walnutfalls** [davidbonnet/astravel#5]
Would it be possible to add support for code like:

var foo = { a: 1};
var bar = {...foo, b: 2};

**Comment by davidbonnet** [comment]
Only stage 4 (finalized) ECMAScript features are supported by default in Astravel. Anything else is experimental.

You could however easily add a node handler for the spread operator, by making a [custom traveler](https://github.com/davidbonnet/astravel#astravelmaketravelerproperties--traveler):
```js
const traveler =  astravel.makeTraveler({
  SpreadProperty(node, state) {
    // Explore `node`…
  }
```
